# Generated by Django 4.0.6 on 2022-07-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='code_file',
            field=models.CharField(max_length=511),
        ),
    ]
