# Generated by Django 4.0.6 on 2023-01-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_alter_solution_code_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='code_file',
            field=models.CharField(max_length=255),
        ),
    ]
