# Generated by Django 4.0.6 on 2023-03-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_alter_solution_code_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_desc',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_input',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_output',
            field=models.CharField(max_length=512),
        ),
    ]
