# Generated by Django 4.0.6 on 2024-01-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_alter_problem_problem_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='example',
            field=models.CharField(default='your_default_value_here', max_length=1024),
        ),
        migrations.AddField(
            model_name='problem',
            name='input',
            field=models.CharField(default='your_default_value_here', max_length=1024),
        ),
        migrations.AddField(
            model_name='problem',
            name='output',
            field=models.CharField(default='your_default_value_here', max_length=1024),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_output',
            field=models.CharField(max_length=1024),
        ),
    ]
